src/BlazorBoilerplate.Client/Pages/Dashboard.razor
The old Chart.Js repository for Blazor from https://github.com/mariusmuntean/ChartJs.Blazor is not maintained any longer. @Joelius300 has created a new fork here: https://github.com/Joelius300/ChartJSBlazor.
=> Updated link to new Chart.Js repository.

src/BlazorBoilerplate.Server/Controllers/AccountController.cs
I refactored the sign in a bit so that it only uses the sign in manager and the Password Sign In. For the difference between the two see here: 
https://stackoverflow.com/questions/53854051/usermanager-checkpasswordasync-vs-signinmanager-passwordsigninasync
Also I changed that the values returned to the best practice to not  provide security relevant information (for example if a user with a particular username exists or not). And it returns the Http Status Code 401 instead of 400 or 404 in case of an invalid login attempt, since the request was valid. Therefore I think this one is a better match.
EDIT: I adjusted the return message for lockout and not allowed (that is for example when your email is not confirmed but you require it). Since you only get these when the provided login …
=> refactor sign in

src/BlazorBoilerplate.Server/Startup.cs, src/BlazorBoilerplate.Server/appsettings.Development.json, src/BlazorBoilerplate.Server/appsettings.json, src/Dockerfile, src/docker-compose.dcproj, src/docker-compose.override.yml, src/docker-compose.yml
Fixes #71 - updated dockerfile, docker-compose.yml to override connetion strings and cleaned up Startup.cs removing duplicate code related to DB setup
------------------------------------------------------------------------------
App runs standalone as always, entrypoint is the Server project.
In docker environment, open CMD / PS and navigate to <repo_root>/Src directory and run
**docker-compose build
docker-compose up -d**
_SqlServer container needs some time to start. Thats why the blazor container is setup with restart policy to try to reconnect until the DB is responding_
**docker-compose down - closes everything down**
In docker-compose.yml, if you want to connect to the SqlServer running **locally** (not the docker sqlserver instance), replace ConnectionStrings__DefaultConnection …
=> Fixes #71 - updated dockerfile, docker-compose.yml

src/BlazorBoilerplate.Client/Pages/Account/Login.razor, src/BlazorBoilerplate.Client/Pages/Account/Profile.razor, src/BlazorBoilerplate.Client/Services/Contracts/IAuthorizeApi.cs, src/BlazorBoilerplate.Client/Services/Implementations/AuthorizeApi.cs, src/BlazorBoilerplate.Client/Services/Implementations/IdentityAuthenticationStateProvider.cs, src/BlazorBoilerplate.Client/Shared/Components/UserProfile.razor, src/BlazorBoilerplate.Client/Shared/Layouts/MainLayout.razor, src/BlazorBoilerplate.Server/Controllers/AccountController.cs
In order to get rid of the 401 error reported in #102 I suggest the following changes:
1. Removing _userInfoCache from the athorization cycle.
2. Bring GetUser into the cycle. It seems that it is much safer to give an unauthorized access to GetUser than GetUserInfo.
some other changes applied to pages and components to be compatible with the new structure.
=> Fix for GetUserInfo 401 error

src/BlazorBoilerplate.Server/Startup.cs
This PR will set the cookie policy on the cookies.
If you receive:
`A cookie associated with a cross-site resource at .... was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`
This means the cookies weren't' set with any Cookie.SameSite attribute. Chrome will soon not allow any cookies that weren't explicitly set like that.
I'm not quite sure if this is something that is fixed in the default cookie policies from Identity, but this fix will be enough to keep …
=> Add SameSite.None to the cookie policy due to Chrome's new cookie policy

src/BlazorBoilerplate.CommonUI/App.razor, src/BlazorBoilerplate.CommonUI/BlazorBoilerplate.CommonUI.csproj, src/BlazorBoilerplate.CommonUI/Services/Implementations/AuthorizeApi.cs, src/BlazorBoilerplate.CommonUI/_Imports.razor, src/BlazorBoilerplate.CommonUI/wwwroot/javascript/jsInterops.js, src/BlazorBoilerplate.Server/Pages/index_ssb.cshtml
Passed the auth cookies received from IdentityServer to/from browser and server to resolve browser refreshes that lose auth information.
=> SSB auth cookies

src/BlazorBoilerplate.Server/Startup.cs, src/BlazorBoilerplate.Storage/ServiceCollectionExtensions.cs
I received several startup errors when trying to run the restructure branch:
Some using statements ins Startup.cs were missing and one variable was declared twice.
Also this:
services.AddIdentity<ApplicationUser, IdentityRole<Guid>>()
.AddRoles<IdentityRole<Guid>>()
.AddEntityFrameworkStores<ApplicationDbContext>()
.AddDefaultTokenProviders();
was in Startup.cs and ServiceCollectionExtensions.cs which causes:
2020-03-09 23:03:05.528 +01:00 [FTL] Application startup exception
System.InvalidOperationException: Scheme already exists: Identity.Application
at Microsoft.AspNetCore.Authentication.AuthenticationOptions.AddScheme(String name, Action`1 configureBuilder)
at Microsoft.AspNetCore.Authentication.AuthenticationBuilder.<>c__DisplayClass4_0`2.<AddSchemeHelper>b__0(AuthenticationOptions o) …
=> Restructure - Startup errors

BlazorBoilerplate.Server.Tests/BlazorBoilerplate.Server.Tests.csproj, azure-pipelines.yml, src/BlazorBoilerplate.CommonUI/BlazorBoilerplate.CommonUI.csproj, src/BlazorBoilerplate.Server/BlazorBoilerplate.Server.csproj, src/BlazorBoilerplate.Storage/BlazorBoilerplate.Storage.csproj
splitting the pipeline changes off from #197 into its own pull req
Basically the same as #200 but with the addition of building both ssb and csb variants (only publishes csb though)
=> bump sdk version to 3.1.200 and switch to UseDotNet@2 task

src/BlazorBoilerplate.CommonUI/Pages/Admin/Roles.razor, src/BlazorBoilerplate.Server/Authorization/AuthorizationPolicyProvider.cs, src/BlazorBoilerplate.Server/Authorization/PermissionRequirement.cs, src/BlazorBoilerplate.Server/Controllers/AccountController.cs, src/BlazorBoilerplate.Server/Controllers/AdminController.cs, src/BlazorBoilerplate.Server/Controllers/ToDoController.cs, src/BlazorBoilerplate.Server/Data/Core/ApplicationPermissions.cs, src/BlazorBoilerplate.Server/Data/DatabaseInitializer.cs, src/BlazorBoilerplate.Server/Startup.cs, src/BlazorBoilerplate.Shared/AuthorizationDefinitions/Permissions.cs
In this PR I suggest a new authorization infrastructure defined as types and constants and provided as a custom authorization policy by [AuthorizationPolicyProvider](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-3.1). 
Main parts:
- **AuthorizationPolicyProvider.cs** : Provides a policy based on a `policyName` we give to authorization system, by using AuthorizeAttribute like this: `[Authorize(policyName)]`. The `policyName` will be just the name of the permission we want to check if the user holds as a claim. Hence, the policy requires the authenticated user to fulfill `PermissionRequirement`.
- **PermissionRequirement.cs** : Checks if the user's role holds a claim of type `permission` with a value equal to the policyName …
=> AuthorizationPolicyProvider based authorization

src/BlazorBoilerplate.Server/Program.cs
What I believe is a trivial update but I'm hoping to offer a few other pull requests over the next few weeks where the sample code I'm working from depends on _Generic Host_ instead of _Web Host_.
=> Migrates to currently recommended (as of 3.x) method of building WebHost

README.md
The current instructions in the README.md for postgres sql db migrations do not work with the new restructuring of DbContext to the BlazorBoilerplate.Storage project.
This fixes it.
=> updated readme with proper instruction for postgres sql db migrations

src/BlazorBoilerplate.CommonUI/Pages/DbLogViewer.razor, src/BlazorBoilerplate.CommonUI/Pages/_Imports.razor, src/BlazorBoilerplate.CommonUI/Shared/Components/NavMenu.razor, src/BlazorBoilerplate.CommonUI/Shared/Components/RefreshTimer.razor, src/BlazorBoilerplate.CommonUI/wwwroot/css/site.css, src/BlazorBoilerplate.Server/Controllers/DbLogController.cs, src/BlazorBoilerplate.Server/Helpers/RegexUtilities.cs, src/BlazorBoilerplate.Server/Managers/DbLogManager.cs, src/BlazorBoilerplate.Server/Managers/IDbLogManager.cs, src/BlazorBoilerplate.Server/Middleware/Wrappers/APIResponse.cs, src/BlazorBoilerplate.Server/Startup.cs, src/BlazorBoilerplate.Server/appsettings.json, src/BlazorBoilerplate.Shared/DataModels/DbLog.cs, src/BlazorBoilerplate.Shared/DataModels/PaginationDetails.cs, src/BlazorBoilerplate.Shared/Dto/ApiResponseDto.cs, src/BlazorBoilerplate.Storage/ApplicationDbContext.cs, src/BlazorBoilerplate.Storage/DatabaseInitializer.cs, src/BlazorBoilerplate.Storage/Migrations/20200326012204_DbLogging.Designer.cs, src/BlazorBoilerplate.Storage/Migrations/20200326012204_DbLogging.cs
Db Log Viewer (currently serilog mssql only).
Added Pagination Property to ApiResponse object to facilitate paginated requests (implemented in /admin/bBlogViewier with MatPaginator)
There may be a slight breaking change if people are relying on serilog db logs going to table Logs2 (renamed to Logs and implemented as a C# efcore object) but I only submitted that pull request a few days ago so ¯\_(ツ)_/¯
It's not perfect: the UI could use a little refinement (specifically table column sizing and automatic refresh interval component) and I'd appreciate it if someone could doublecheck my efcore db log query (I'm pretty sure there's a more efficient way of getting ordered logs but I can't think of it now).
It works though
=> Dev db log viewer

src/BlazorBoilerplate.CommonUI/Pages/Admin/DbLogViewer.razor, src/BlazorBoilerplate.CommonUI/Shared/Components/RefreshTimer.razor, src/BlazorBoilerplate.CommonUI/wwwroot/css/site.css, src/BlazorBoilerplate.Server/Controllers/DbLogController.cs, src/BlazorBoilerplate.Server/Managers/DbLogManager.cs, src/BlazorBoilerplate.Server/Managers/IDbLogManager.cs, src/BlazorBoilerplate.Shared/DataModels/DbLog.cs, src/BlazorBoilerplate.Shared/DataModels/PaginationDetails.cs, src/BlazorBoilerplate.Storage/ApplicationDbContext.cs, src/BlazorBoilerplate.Storage/Migrations/20200329024307_MultiTenantMigration.Designer.cs, src/BlazorBoilerplate.Storage/Migrations/20200329024307_MultiTenantMigration.cs, src/BlazorBoilerplate.Storage/Migrations/20200329024357_SQLDbLoggingMigration.Designer.cs, src/BlazorBoilerplate.Storage/Migrations/20200329024357_SQLDbLoggingMigration.cs
Added Delta Query Support for DbLog Api/Viewing page.
Separated Dblog migration from Multitenant Migration (Whoops my bad)
Tried some optimization for DbLog Table and log queries in general.  It's not going to get anywhere near the performance of real logging applications like graylog but it's better than nothing?  
Breaking Change: This will require deleting and remaking any existing databases due to redoing / separating  the db logging migration
=> Db Log improvements, fixed accidental migration lumping, delta query support

src/Server/BlazorBoilerplate.Server/Pages/Login.cshtml.cs, src/Shared/Modules/BlazorBoilerplate.Theme.Material/Shared/Components/Breadcrumbs.razor
using `string.Empty` as empty `ReturnUrl ` caused 'value can not be empty' error in `localRedirect` of login page. Replacing with `"/"` fixes the problem.
=> ReturnUrl patch

src/Shared/Modules/BlazorBoilerplate.Theme.Material.Demo/Pages/Dashboard.razor
First of all, sorry for not opening an issue. I thought this change is small enough to just submit the PR directly.
The old repo ([Joelius300/ChartJSBlazor](https://github.com/Joelius300/ChartJSBlazor)) was archived a while ago and all the new development takes place back on the original repo [mariusmuntean/ChartJs.Blazor](https://github.com/mariusmuntean/ChartJs.Blazor).
You should check out the new [2.0 release](https://github.com/mariusmuntean/ChartJs.Blazor/releases/tag/v2.0.0) if you're interested.
Basically reverts https://github.com/enkodellc/blazorboilerplate/pull/12 but I also removed the IMO unnecessary part of the link text (the `https://github.com`).
Also, @enkodellc are you still interested in adding a sample chart to your project? You mentioned that in the linked PR.
=> Update the ChartJs.Blazor link again

README.md, src/Server/BlazorBoilerplate.Server/BlazorBoilerplate.Server.csproj, src/Server/BlazorBoilerplate.Server/Startup.cs
Need to update doc to correlate with code change. We need to conform to the standards of what .net supports. See https://docs.microsoft.com/en-us/dotnet/standard/security/cross-platform-cryptography and lookup CurrentUser\My vs LocalMachine\My. Nowhere is there "WebHosting".
We should also allow user secrets. See https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-5.0
=> only use StoreName.My in Linux

README.md, src/Server/BlazorBoilerplate.Server/Startup.cs, src/Utils/Docker/Dockerfile, src/Utils/Docker/docker-compose.yml
Assuming the docker config is broken, I am attempting to get it fixed. Also, I wanted to document the connection scenarios depending on how one connects when using a self signed cert. The error is expected, but stressful if it's not a known error. Allowing some flexibility in the dev environment around self signed certificates seems ok to me. Everyone should know not to run in Development environment in Production.
=> fix docker config; add dev env flexability;

src/Shared/Modules/BlazorBoilerplate.Theme.Material.Demo/Hubs/ChatClient.cs
Using the equivalent of Path.Combine to combine a base url with its fragment. new Uri(base,fragment)
=> combine BaseAddress with chathub

README.md, src/Server/BlazorBoilerplate.Storage/ServiceCollectionExtensions.cs
Per @GioviQ
When MultipleActiveResultSets=false, will lead to error: 
An exception occurred while iterating over the results of a query for context type 'BlazorBoilerplate.Storage.LocalizationDbContext'.
System.InvalidOperationException: There is already an open DataReader associated with this Connection which must be closed first.
=> require MultipleActiveResultSets=true

src/Server/BlazorBoilerplate.Server/Pages/_Index.cshtml, src/Shared/Modules/BlazorBoilerplate.Theme.Material/Shared/Layouts/MainLayout.razor.css, src/Shared/Modules/BlazorBoilerplate.Theme.Material/wwwroot/css/site.css
Left Nav Bar wraps in mobile view. Try it out in the f12 dev tools, switch to mobile view. This doesn't fix the overlap, but at least it doesn't wrap (looks less buggy)
=> Add css isolation for Razor class library (RCL) BlazorBoilerplate.Theme.Material Module

src/Utils/Terraform/AWS/bash.tmpl
I noticed the hd fills up after some time, but this pull request should prevent it
=> prevent docker logging from filling hd

src/Shared/BlazorBoilerplate.UI.Base/Shared/Components/TopSection.cs
If the razor page does not have a layout and has a top section it will error. This at least prevents the error. Possible better solution is to show an error.  @GioviQ  any suggestions.
=> Handle missing Layout for TopSection

src/Shared/BlazorBoilerplate.Shared.Localizer/LocalizationProvider.cs
fix for PostgreSQL :  Npgsql.NpgsqlOperationInProgressException: A command is already in progress
Because multiple inner queries on the same PostgresSQL connection results in the "A command is already in progress" exception...
By splitting three queries, the problem was solved.
=> Update for PostgreSQL Combability  ( Multiple Resultset fix)

src/Server/BlazorBoilerplate.Server/Managers/AccountManager.cs
Person objects were previously only created correctly in ExternalAuthManager.ExternalSignIn but now they are also correctly created correctly in AccountManager.UpdateUser and AccountManager.AdminUpdateUser.
=> Fix: Person ids not being generated on creation
