- src/BlazorBoilerplate.Client/Shared/MainLayout.razor
FIX error bug #7, just added the RefBack
> FIX error bug #7

- src/BlazorBoilerplate.Client/Pages/TestEmailView.razor
- src/BlazorBoilerplate.Client/Shared/NavMenu.razor
- src/BlazorBoilerplate.Server/Controllers/EmailController.cs
- src/BlazorBoilerplate.Server/Helpers/EmailTemplates.cs
- src/BlazorBoilerplate.Server/Models/EmailConfiguration.cs
- src/BlazorBoilerplate.Server/Services/EmailService.cs
- src/BlazorBoilerplate.Server/appsettings.Development.json
- src/BlazorBoilerplate.Server/appsettings.json
- src/BlazorBoilerplate.Shared/EmailAddress.cs
- src/BlazorBoilerplate.Shared/EmailMessage.cs
Added pop3 and IMAP email retrieval along with a crude viewing page
> Email Retrieval Support

- src/BlazorBoilerplate.Client/Pages/BlazorMiddlewareAudit.razor
Fixes https://github.com/enkodellc/blazorboilerplate/issues/28.
> Fixed spelling issues on the audit log page.

- src/BlazorBoilerplate.Client/Pages/Admin/Users.razor
- src/BlazorBoilerplate.Server/Controllers/AccountController.cs
> Added manual password reset for Admin Dashboard

- src/BlazorBoilerplate.Client/Startup.cs
- src/BlazorBoilerplate.Client/_Imports.razor
- src/BlazorBoilerplate.Server/Authorization/AdditionalUserClaimsPrincipalFactory.cs
- src/BlazorBoilerplate.Server/Controllers/AccountController.cs
- src/BlazorBoilerplate.Server/Startup.cs
- src/BlazorBoilerplate.Shared/AuthorizationDefinitions/Policies.cs
- src/BlazorBoilerplate.Shared/AuthorizationDefinitions/Requirements.cs
- src/BlazorBoilerplate.Shared/BlazorBoilerplate.Shared.csproj
Migrated  to centralized authentication policy definitions, added client-side authentication policy awareness, added example authentication policy requirement logic.
> Authentication policies management centralized 

- src/BlazorBoilerplate.Server/BlazorBoilerplate.Server.csproj
- src/BlazorBoilerplate.Server/Startup.cs
- src/BlazorBoilerplate.sln
- src/TempCertGenerator/Program.cs
- src/TempCertGenerator/TempCertGenerator.csproj
Added temp cert generator (as side project so it's easier and more obvious to remove) so we don't have the same private key being reused (and abused)
> Added temporary cert generator

- src/BlazorBoilerplate.Client/Pages/Admin/Users.razor
- src/BlazorBoilerplate.Server/Controllers/AccountController.cs
- src/BlazorBoilerplate.Server/Controllers/ApiLogController.cs
- src/BlazorBoilerplate.Server/Controllers/EmailController.cs
- src/BlazorBoilerplate.Server/Controllers/SampleDataController.cs
- src/BlazorBoilerplate.Server/Controllers/UserProfileController.cs
- src/BlazorBoilerplate.Server/Data/DatabaseInitializer.cs
- src/BlazorBoilerplate.Server/Data/IdentityServerConfig.cs
- src/BlazorBoilerplate.Server/Properties/launchSettings.json
- src/BlazorBoilerplate.Server/Startup.cs
- src/BlazorBoilerplate.Shared/AuthorizationDefinitions/Policies.cs
Switching to claims based authentication as IS4 seems to have issues with roles.  Was able to get the api authentication working.
TODO: User administration screen needs to be updated to modify claims instead of roles
> Started switching from role based auth to claims based

- src/BlazorBoilerplate.Server/Middleware/UserSessionMiddleware.cs
- src/BlazorBoilerplate.Server/Startup.cs
Fixes #73 - changed middleware order to first authenticate than store user session. Inside usersession middleware, first store the data then call next middlewae in pipeline
> Fixes #73 - changed user session middleware order

- src/BlazorBoilerplate.Server/appsettings.json
Fix for Email configuration. to fix issue 88
> Update appsettings.json to fix 

- README.md
- src/BlazorBoilerplate.Client/Pages/Account/Login.razor
- src/BlazorBoilerplate.Server/Controllers/AccountController.cs
- src/BlazorBoilerplate.Server/Services/UserProfileService.cs
> Fix Login Page Blip

- src/BlazorBoilerplate.CommonUI/Pages/Account/Login.razor
- src/BlazorBoilerplate.CommonUI/Shared/Layouts/MainLayout.razor
Pages code modified to exit from Login Dialog to the caller page.
https://github.com/enkodellc/blazorboilerplate/issues/139
> Fixed: Exit from Login dialog #139

- src/BlazorBoilerplate.Server/Data/DatabaseInitializer.cs
`SeedAsync` function should be "public virtual...
> minor tweaks

- src/BlazorBoilerplate.CommonUI/Pages/BlazorMiddlewareAudit.razor
This adds a refresh button as requested in issue #143 
New to Blazor in general so let me know if any changes are needed.
> Refresh API log table data

- azure-pipelines.yml
This fixes the il-linker build error seen in #195 and #197 and #201
> bump sdk version to 3.1.200 and switch to UseDotNet@2 task

- src/BlazorBoilerplate.CommonUI/Pages/Account/Register.razor
- src/BlazorBoilerplate.CommonUI/Pages/Admin/Roles.razor
- src/BlazorBoilerplate.CommonUI/Pages/Admin/Users.razor
- src/BlazorBoilerplate.CommonUI/Pages/TodoList.razor
- src/BlazorBoilerplate.Server/Authorization/PermissionRequirement .cs
- src/BlazorBoilerplate.Server/Managers/AccountManager.cs
- src/BlazorBoilerplate.Server/Managers/AdminManager.cs
- src/BlazorBoilerplate.Server/Managers/ApiLogManager.cs
- src/BlazorBoilerplate.Server/Managers/ToDoManager.cs
- src/BlazorBoilerplate.Server/Managers/UserProfileManager.cs
- src/BlazorBoilerplate.Server/Middleware/Wrappers/APIResponse.cs
- src/BlazorBoilerplate.Server/Startup.cs
- src/BlazorBoilerplate.Shared/DataInterfaces/IApiLogStore.cs
- src/BlazorBoilerplate.Shared/DataInterfaces/IToDoStore.cs
- src/BlazorBoilerplate.Shared/Dto/ApiResponseDto.cs
- src/BlazorBoilerplate.Storage/Stores/ApiLogStore.cs
- src/BlazorBoilerplate.Storage/Stores/ToDoStore.cs
- src/BlazorBoilerplate.Storage/Stores/UserProfileStore.cs
Refactoring.
Delete localdb to test. No issue detected related to async await.
> Restore async await and some bug fix.

- src/BlazorBoilerplate.Client/BlazorBoilerplate.Client.csproj
- src/BlazorBoilerplate.Client/Properties/launchSettings.json
- src/BlazorBoilerplate.CommonUI/BlazorBoilerplate.CommonUI.csproj
- src/BlazorBoilerplate.CommonUI/Pages/Account/Profile.razor
- src/BlazorBoilerplate.CommonUI/Pages/Admin/Roles.razor
- src/BlazorBoilerplate.CommonUI/Pages/Admin/Users.razor
- src/BlazorBoilerplate.CommonUI/Pages/BlazorMiddlewareAudit.razor
- src/BlazorBoilerplate.CommonUI/Pages/TestEmailView.razor
- src/BlazorBoilerplate.CommonUI/Pages/TodoList.razor
- src/BlazorBoilerplate.CommonUI/_Imports.razor
- src/BlazorBoilerplate.Server/BlazorBoilerplate.Server.csproj
- src/BlazorBoilerplate.Server/Properties/launchSettings.json
- src/BlazorBoilerplate.Shared/Dto/BaseDto.cs
- src/BlazorBoilerplate.Shared/Dto/IMementoDto.cs
- src/BlazorBoilerplate.Storage/BlazorBoilerplate.Storage.csproj
- src/BlazorBoilerplate.Storage/DatabaseInitializer.cs
nuget update
upgrade to https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available/
successful CRUD test on users
inspectUri does not enable debug. Maybe I miss something...
> blazor-webassembly-3-2-0-preview-3

- src/BlazorBoilerplate.Server/BlazorBoilerplate.Server.csproj
MatBlazor was refernced two times
> Fix duplicate referance

- src/Shared/BlazorBoilerplate.Localization/Settings.cs
- src/Shared/BlazorBoilerplate.Localization/Strings.de-DE.resx
Added a german translation of the existing .rsx localization file
> German localization

- src/Server/BlazorBoilerplate.Server/Extensions/ModuleLoader.cs
- src/Server/BlazorBoilerplate.Server/Startup.cs
- src/Shared/Modules/BlazorBoilerplate.GoogleAnalytics/BlazorBoilerplate.GoogleAnalytics.csproj
- src/Shared/Modules/BlazorBoilerplate.Theme.Material.Admin/BlazorBoilerplate.Theme.Material.Admin.csproj
- src/Shared/Modules/BlazorBoilerplate.Theme.Material.Demo/BlazorBoilerplate.Theme.Material.Demo.csproj
- src/Shared/Modules/BlazorBoilerplate.Theme.Material/BlazorBoilerplate.Theme.Material.csproj
I am not using Windows, and I was able to get it working on Linux. I have a sequence of changes I would like to make. This pull request seems like a good place to start.
> Use Copy instead of Exec (works on linux)

- README.md
- src/Server/BlazorBoilerplate.Server/Startup.cs
- src/Utils/Docker/Dockerfile
- src/Utils/Docker/docker-compose.yml
Just trying to add clarity. Depending on how you connect, environment is in Development vs Production, clarify whether login will work, and in what cases an error will occur.
> clerify the Docker Support notes

- src/Utils/Terraform/AWS/bash.tmpl
- src/Utils/Terraform/AWS/docker-compose.tpl
aws deployment script needs to configure host to start docker on bootup
> start docker containers on boot

- src/Utils/Docker/Dockerfile
Fix for https://github.com/enkodellc/blazorboilerplate/issues/669
> increment asp.net core version

- src/Utils/Terraform/AWS/main.tf
> mem requirements are now too high for t2.micro

- src/Clients/Maui/Pages/UsersPage.razor.cs
- src/Server/BlazorBoilerplate.Server/Controllers/ApplicationController.cs
- src/Shared/BlazorBoilerplate.Shared/Models/UserFilter.cs
- src/Shared/BlazorBoilerplate.UI.Base/Pages/Admin/Users.cs
- src/Shared/BlazorBoilerplate.UI.Base/Shared/Components/ItemsTableBase.cs
- src/Shared/Modules/BlazorBoilerplate.Theme.MudBlazor.Admin/Pages/Admin/Users.razor
- src/Shared/Modules/BlazorBoilerplate.Theme.MudBlazor.Main/Pages/UsersPage.razor.cs
Also moved ItemsTableBase<T> to UI.Base.Shared.Componenents, where I believe it belongs. It inherits from BaseComponent which is in that namespace and it is used everywhere. Being in Theme.MudBlazor meant that no page or component in UI.Base could use it, but now it can be used anywhere. 
Searching on the admin page is automatic on input but limited to one server call per 1.5 seconds.
> Added ability for admin to search and filter users

- README.md
- src/Server/BlazorBoilerplate.Server/Managers/AdminManager.cs
- src/Server/BlazorBoilerplate.Storage/DatabaseInitializer.cs
- src/Server/BlazorBoilerplate.Storage/Mapping/IdentityServer4MappingExtensions.cs
Fixes #978
The issue seems to be IdentityServer4's mapping profiles in net7.0. It is not fixed by using a higher version of AutoMapper. I solved the problem by just writing manual mapping extensions for everything.
> Fix Master branch / net 7.0
